myserver : AcceptTCPConnection.c CreateTCPServerSocket.c  DieWithError.c  HandleTCPClient.c TCPEcho-Server-Fork.c TCPEchoServer.h
	gcc -o $@ TCPEcho-Server-Fork.c AcceptTCPConnection.c CreateTCPServerSocket.c  DieWithError.c  HandleTCPClient.c
clean:
	rm -i *.o
